set(CMAKE_SYSTEM_NAME $ENV{SYTEM_NAME})
set(CMAKE_SYSTEM_PROCESSOR $ENV{SYSTEM_ARCH})

set(CMAKE_C_COMPILER $ENV{CC})
set(CMAKE_CXX_COMPILER $ENV{CXX})
set(CMAKE_LINKER $ENV{LD})

set(CMAKE_C_FLAGS $ENV{CFLAGS})
set(CMAKE_CXX_FLAGS $ENV{CXXFLAGS})