#!/bin/bash

export CROSS_COMPILE=/usr/bin/arm-linux-gnueabihf-
export CROSS_COMPILE_VERSION=-10

export SYSTEM_NAME=Linux
export SYSTEM_ARCH=arm

export CC=${CROSS_COMPILE}gcc${CROSS_COMPILE_VERSION}
export CXX=${CROSS_COMPILE}g++${CROSS_COMPILE_VERSION}
export LD=${CROSS_COMPILE}ld

export CFLAGS="-march=armv7-a -mfpu=vfpv4 -mfloat-abi=hard -O2 -Wall"
export CXXFLAGS="$CFLAGS -std=c++20"
